"""Generated protobuf stubs for the AI Cluster gRPC protocol.

These modules are typically auto-generated by grpc_tools.protoc from
``proto/cluster.proto``.  The files in this package provide minimal
stub implementations so that the coordinator can be imported and tested
without running the protobuf compiler first.

To regenerate from the real .proto file:

    python -m grpc_tools.protoc \
        -I../../proto \
        --python_out=. \
        --grpc_python_out=. \
        ../../proto/cluster.proto
"""
