# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import cluster_pb2 as cluster__pb2
import grpc

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in cluster_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class WorkerStub(object):
    """Worker service - runs on each GPU node
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.LoadModel = channel.unary_unary(
                '/cluster.Worker/LoadModel',
                request_serializer=cluster__pb2.LoadModelRequest.SerializeToString,
                response_deserializer=cluster__pb2.LoadModelResponse.FromString,
                _registered_method=True)
        self.Infer = channel.unary_stream(
                '/cluster.Worker/Infer',
                request_serializer=cluster__pb2.InferenceRequest.SerializeToString,
                response_deserializer=cluster__pb2.InferenceResponse.FromString,
                _registered_method=True)
        self.GetStatus = channel.unary_unary(
                '/cluster.Worker/GetStatus',
                request_serializer=cluster__pb2.Empty.SerializeToString,
                response_deserializer=cluster__pb2.WorkerStatus.FromString,
                _registered_method=True)
        self.UnloadModel = channel.unary_unary(
                '/cluster.Worker/UnloadModel',
                request_serializer=cluster__pb2.UnloadModelRequest.SerializeToString,
                response_deserializer=cluster__pb2.Empty.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/cluster.Worker/HealthCheck',
                request_serializer=cluster__pb2.Empty.SerializeToString,
                response_deserializer=cluster__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class WorkerServicer(object):
    """Worker service - runs on each GPU node
    """

    def LoadModel(self, request, context):
        """Load a model onto the worker's GPU(s)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Infer(self, request, context):
        """Run inference on loaded model
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatus(self, request, context):
        """Get worker status (GPUs, memory, health)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnloadModel(self, request, context):
        """Unload model and free GPU memory
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health check for liveness probes
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WorkerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'LoadModel': grpc.unary_unary_rpc_method_handler(
                    servicer.LoadModel,
                    request_deserializer=cluster__pb2.LoadModelRequest.FromString,
                    response_serializer=cluster__pb2.LoadModelResponse.SerializeToString,
            ),
            'Infer': grpc.unary_stream_rpc_method_handler(
                    servicer.Infer,
                    request_deserializer=cluster__pb2.InferenceRequest.FromString,
                    response_serializer=cluster__pb2.InferenceResponse.SerializeToString,
            ),
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=cluster__pb2.Empty.FromString,
                    response_serializer=cluster__pb2.WorkerStatus.SerializeToString,
            ),
            'UnloadModel': grpc.unary_unary_rpc_method_handler(
                    servicer.UnloadModel,
                    request_deserializer=cluster__pb2.UnloadModelRequest.FromString,
                    response_serializer=cluster__pb2.Empty.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=cluster__pb2.Empty.FromString,
                    response_serializer=cluster__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cluster.Worker', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cluster.Worker', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Worker(object):
    """Worker service - runs on each GPU node
    """

    @staticmethod
    def LoadModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cluster.Worker/LoadModel',
            cluster__pb2.LoadModelRequest.SerializeToString,
            cluster__pb2.LoadModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Infer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/cluster.Worker/Infer',
            cluster__pb2.InferenceRequest.SerializeToString,
            cluster__pb2.InferenceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cluster.Worker/GetStatus',
            cluster__pb2.Empty.SerializeToString,
            cluster__pb2.WorkerStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnloadModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cluster.Worker/UnloadModel',
            cluster__pb2.UnloadModelRequest.SerializeToString,
            cluster__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cluster.Worker/HealthCheck',
            cluster__pb2.Empty.SerializeToString,
            cluster__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
